---

#- name: Install prerequisite packages for Jekyll
#  apt: pkg={{ item }} state=present update_cache=yes
#  with_items:
#    -

### Install the Jekyll source

- include: ../../rvm/tasks/bundler.yml
  vars:
    rvm_user: "{{ jekyll.user }}"
    ruby_version: "{{ ruby.global }}"
    bundler_path: "{{ jekyll.path }}"

- name: Install Jekyll Nginx.conf
  template: src='nginx.conf.j2' dest='/etc/nginx/conf.d/nginx.conf'
  notify: restart nginx

- name: Install Gulp
  npm: name={{ item }} path={{ jekyll.path }} global=yes
  with_items:
    - gulp
    - forever

- name: Install NPM Packages
  command: npm install

#- name: Check if running
  #command: "{{ jekyll.path }}/node_modules/.bin/forever list"
  #register: forever_list
  #changed_when: false

#- name: Start Gulp
  #command: npm start chdir={{ jekyll.path }}
  #when: "forever_list.stdout.find('node_modules/.bin/gulp') == -1"
